In [1]:
import pandas as pd
import numpy as np

In [2]:
name = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
df = pd.read_csv('iris.data', sep=',', names=name)
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
iris_data = pd.get_dummies(data=df, columns=['class'])
iris_data.head()

sepal_length  sepal_width  petal_length  petal_width  class_Iris-setosa  \
0           5.1          3.5           1.4          0.2                  1   
1           4.9          3.0           1.4          0.2                  1   
2           4.7          3.2           1.3          0.2                  1   
3           4.6          3.1           1.5          0.2                  1   
4           5.0          3.6           1.4          0.2                  1   

   class_Iris-versicolor  class_Iris-virginica  
0                      0                     0  
1                      0                     0  
2                      0                     0  
3                      0                     0  
4                      0                     0

In [4]:
X = iris_data.iloc[:, :4]
y = iris_data.iloc[:, 4:7]

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, test_size=0.2)

In [6]:
y_train_setosa = y_train.iloc[:, 0]
y_train_versicolor = y_train.iloc[:, 1]
y_train_virginica = y_train.iloc[:, 2]
print(y_train_setosa.head())
print(y_train_versicolor.head())
print(y_train_virginica.head())

91     0
135    0
69     0
128    0
114    0
Name: class_Iris-setosa, dtype: uint8
91     1
135    0
69     1
128    0
114    0
Name: class_Iris-versicolor, dtype: uint8
91     0
135    1
69     0
128    1
114    1
Name: class_Iris-virginica, dtype: uint8


In [7]:
y_test_setosa = y_test.iloc[:, 0]
y_test_versicolor = y_test.iloc[:, 1]
y_test_virginica = y_test.iloc[:, 2]
print(y_test_setosa.head())
print(y_test_versicolor.head())
print(y_test_virginica.head())
print(X_test.head())

14     1
98     0
75     0
16     1
131    0
Name: class_Iris-setosa, dtype: uint8
14     0
98     1
75     1
16     0
131    0
Name: class_Iris-versicolor, dtype: uint8
14     0
98     0
75     0
16     0
131    1
Name: class_Iris-virginica, dtype: uint8
     sepal_length  sepal_width  petal_length  petal_width
14            5.8          4.0           1.2          0.2
98            5.1          2.5           3.0          1.1
75            6.6          3.0           4.4          1.4
16            5.4          3.9           1.3          0.4
131           7.9          3.8           6.4          2.0


In [8]:
X_train = X_train.to_numpy()
X_test = X_test.to_numpy()
y_train_setosa = y_train_setosa.to_numpy()
y_train_versicolor = y_train_versicolor.to_numpy()
y_train_virginica = y_train_virginica.to_numpy()
y_test_setosa = y_test_setosa.to_numpy()
y_test_versicolor = y_test_versicolor.to_numpy()
y_test_virginica = y_test_virginica.to_numpy()
y_test = y_test.to_numpy()

In [9]:
def predict(input, weights, bias):
    weighted_sum = np.dot(input, weights) + bias
    output = 1 if weighted_sum > 0.6 else 0
    return output

In [10]:
def train_weights(epochs, learning_rate, input, output, weights, bias):
    for _ in range(epochs):
        for i in range(len(input)):
            predicted = predict(input[i], weights, bias)
            error = output[i] - predicted
            weights += learning_rate * error * input[i]
            bias += learning_rate * error

In [11]:
weights_setosa = np.ones((4,))
weights_versicolor = np.ones((4,))
weights_virginica = np.ones((4,))
bias_setosa, bias_versicolor, bias_virginica = 0, 0, 0

In [12]:
train_weights(200, 0.01, X_train, y_train_setosa, weights_setosa, bias_setosa)
train_weights(200, 0.01, X_train, y_train_versicolor, weights_versicolor, bias_versicolor)
train_weights(200, 0.01, X_train, y_train_virginica, weights_virginica, bias_virginica)

In [13]:
print(weights_setosa)
print(bias_setosa)
print(weights_versicolor)
print(bias_versicolor)
print(weights_virginica)
print(bias_virginica)

[-0.079  0.681 -0.412  0.413]
0
[ 0.055 -0.493  0.241 -0.59 ]
0
[-0.662 -0.645  0.943  1.478]
0


In [14]:
print(predict([5.8, 4.0, 1.2, 0.2], weights_setosa, bias_setosa))
print(predict([5.8, 4.0, 1.2, 0.2], weights_versicolor, bias_versicolor))
print(predict([5.8, 4.0, 1.2, 0.2], weights_virginica, bias_virginica))

1
0
0


## Testing

In [15]:
def test(input, output):
    correct_pred = 0
    for i in range(len(output)):
        result = []
        result.append(predict(input[i], weights_setosa, bias_setosa))
        result.append(predict(input[i], weights_versicolor, bias_versicolor))
        result.append(predict(input[i], weights_virginica, bias_virginica))
        check = output[i].tolist()
        print(result, " ", check)
        if result == check:
            correct_pred += 1
    print("Correct Prediction: ", correct_pred)
    print("Total Tests: ", len(output))
    print("Accuracy: ", correct_pred/len(output))
        

In [16]:
test(X_test, y_test)

[1, 0, 0]   [1, 0, 0]
[0, 0, 0]   [0, 1, 0]
[0, 0, 0]   [0, 1, 0]
[1, 0, 0]   [1, 0, 0]
[0, 0, 1]   [0, 0, 1]
[0, 0, 0]   [0, 1, 0]
[0, 0, 1]   [0, 0, 1]
[1, 0, 0]   [1, 0, 0]
[1, 0, 0]   [1, 0, 0]
[0, 0, 1]   [0, 0, 1]
[0, 0, 0]   [0, 1, 0]
[1, 0, 0]   [1, 0, 0]
[0, 0, 1]   [0, 0, 1]
[0, 0, 0]   [0, 1, 0]
[0, 0, 1]   [0, 1, 0]
[1, 0, 0]   [1, 0, 0]
[0, 0, 0]   [0, 1, 0]
[0, 0, 1]   [0, 1, 0]
[1, 0, 0]   [1, 0, 0]
[1, 0, 0]   [1, 0, 0]
[0, 0, 1]   [0, 1, 0]
[0, 0, 1]   [0, 1, 0]
[0, 0, 1]   [0, 1, 0]
[1, 0, 0]   [1, 0, 0]
[0, 0, 1]   [0, 0, 1]
[0, 0, 0]   [0, 1, 0]
[1, 0, 0]   [1, 0, 0]
[1, 0, 0]   [1, 0, 0]
[0, 0, 0]   [0, 1, 0]
[0, 0, 1]   [0, 0, 1]
Correct Prediction:  17
Total Tests:  30
Accuracy:  0.5666666666666667


In [17]:
def testSingle(test_set, test_output):
    correct_pred = 0
    result = []
    for i in range(len(test_set)):
        prediction = predict(test_set[i], weights=weights_versicolor, bias=bias_versicolor)
        result.append(prediction)
        if prediction == test_output[i]:
            correct_pred += 1
    print(np.array(result))
    print(test_output)
    print("Correct Prediction: ", correct_pred)
    print("Total tests: ", len(test_set))

In [18]:
testSingle(X_test, y_test_versicolor)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 1 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0]
Correct Prediction:  17
Total tests:  30
