## Numpy

In [10]:
import numpy as np

In [11]:
a = np.array([1, 2, 3, 4, 5])
print(a.shape)
print(a.ndim)

(5,)
1


In [12]:
b = np.array([[1, 2], [3, 4]])
print(b.shape)
print(b.ndim)

(2, 2)
2


In [13]:
# n-dimensional array
nd = np.array([1, 2, 3],ndmin=5)
print(nd)
print(nd.shape)

[[[[[1 2 3]]]]]
(1, 1, 1, 1, 3)


### Slicing of arrays

In [14]:
print(b[0][1])
print(b[0, 1])
print(b[-1, -2])

2
2
3


Copy and View

In [15]:
a1 = np.array([1, 2, 3])
x = a1.copy()
x[0] = 0
print(a1, x)

[1 2 3] [0 2 3]


In [21]:
x = a1.view()
x[0] = 0
print(a1, x)

[0 2 3] [0 2 3]


In [24]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
for x in a2:
    for y in x:
        print(y)

1
2
3
4
5
6


Concatenating (Joining) two Arrays

In [27]:
# concatenating by rows (axis=0)
ar1 = np.array([[1, 2], [3, 4]])
ar2 = np.array([[5, 6], [7, 8]])
arr3 = np.concatenate((ar1, ar2), axis=0)
arr3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
# concatenating by columns (axis=1)
ar1 = np.array([[1, 2], [3, 4]])
ar2 = np.array([[5, 6], [7, 8]])
arr3 = np.concatenate((ar1, ar2), axis=1)
arr3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Splitting of arrays

In [36]:
joint_array = np.array([1, 2, 3, 4, 5, 6])
new = np.split(joint_array, 3)
for i in new:
    print(i)

[1 2]
[3 4]
[5 6]


Random module from Numpy

In [69]:
rnd = np.random.randint(100, size=(2, 4))
print(rnd)

[[96 58 93 12]
 [62 63 94 87]]


In [90]:
rnd_f = np.random.rand(2, 4)
rnd+rnd_f

array([[96.29934122, 58.76447714, 93.47367444, 12.55191938],
       [62.27935044, 63.23735579, 94.09097247, 87.02708628]])

In [91]:

uni = np.random.uniform(low=2, high=5, size=(2, 4))
uni

array([[2.86772991, 3.77575488, 3.2577647 , 4.02063169],
       [2.75092897, 2.06187438, 3.62957052, 3.52428489]])