## Numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a.shape)
print(a.ndim)

(5,)
1


In [4]:
b = np.array([[1, 2], [3, 4]])
print(b.shape)
print(b.ndim)

(2, 2)
2


In [5]:
# n-dimensional array
nd = np.array([1, 2, 3],ndmin=5)
print(nd)
print(nd.shape)

[[[[[1 2 3]]]]]
(1, 1, 1, 1, 3)


Slicing of arrays

In [6]:
print(b[0][1])
print(b[0, 1])
print(b[-1, -2])

2
2
3


Copy and View

In [7]:
a1 = np.array([1, 2, 3])
x = a1.copy()
x[0] = 0
print(a1, x)

[1 2 3] [0 2 3]


In [8]:
x = a1.view()
x[0] = 0
print(a1, x)

[0 2 3] [0 2 3]


In [9]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
for x in a2:
    for y in x:
        print(y)

1
2
3
4
5
6


Concatenating (Joining) two Arrays

In [10]:
# concatenating by rows (axis=0)
ar1 = np.array([[1, 2], [3, 4]])
ar2 = np.array([[5, 6], [7, 8]])
arr3 = np.concatenate((ar1, ar2), axis=0)
arr3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
# concatenating by columns (axis=1)
ar1 = np.array([[1, 2], [3, 4]])
ar2 = np.array([[5, 6], [7, 8]])
arr3 = np.concatenate((ar1, ar2), axis=1)
arr3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Splitting of arrays

In [12]:
joint_array = np.array([1, 2, 3, 4, 5, 6])
new = np.split(joint_array, 3)
for i in new:
    print(i)

[1 2]
[3 4]
[5 6]


Random module from Numpy

In [13]:
rnd = np.random.randint(100, size=(2, 4))
print(rnd)

[[85 27 68 50]
 [49 12 51 73]]


In [14]:
rnd_f = np.random.rand(2, 4)
rnd+rnd_f 

array([[85.48200748, 27.83139623, 68.07832451, 50.79253558],
       [49.16806783, 12.71303325, 51.82010609, 73.25147669]])

In [15]:

uni = np.random.uniform(low=2, high=5, size=(2, 4))
uni

array([[4.39077969, 2.00739119, 3.10580057, 4.01833232],
       [4.36376706, 2.13617269, 3.55681898, 3.61632351]])

In [36]:
x = np.random.choice(a=[1, 2, 3, 4], p=[0.3, 0.6, 0.1, 0.0])
print(x)

2


In [37]:
x = np.random.normal(loc=0, scale=1, size=(2))
print(x)

[ 1.14670049 -0.6648787 ]
