In [27]:
import pandas as pd
import numpy as np

## Importing Dataset and Encoding Categorical Values

In [28]:
name = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
dataset = pd.read_csv("iris.data", sep=',', names= name)

In [29]:
iris_data = pd.get_dummies(dataset, columns=['class'])
print(iris_data)

     sepal_length  sepal_width  petal_length  petal_width  class_Iris-setosa  \
0             5.1          3.5           1.4          0.2                  1   
1             4.9          3.0           1.4          0.2                  1   
2             4.7          3.2           1.3          0.2                  1   
3             4.6          3.1           1.5          0.2                  1   
4             5.0          3.6           1.4          0.2                  1   
..            ...          ...           ...          ...                ...   
145           6.7          3.0           5.2          2.3                  0   
146           6.3          2.5           5.0          1.9                  0   
147           6.5          3.0           5.2          2.0                  0   
148           6.2          3.4           5.4          2.3                  0   
149           5.9          3.0           5.1          1.8                  0   

     class_Iris-versicolor  class_Iris-

In [30]:
X = iris_data.iloc[:, :4]
y = iris_data.iloc[:, 4]
print(X)
print(y)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]
0      1
1      1
2      1
3      1
4      1
      ..
145    0
146    0
147    0
148    0
149    0
Name: class_Iris-setosa, Length: 150, dtype: uint8


## Splitting of Training and Testing Sets

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, test_size=0.2)

In [32]:
X_train

sepal_length  sepal_width  petal_length  petal_width
91            6.1          3.0           4.6          1.4
135           7.7          3.0           6.1          2.3
69            5.6          2.5           3.9          1.1
128           6.4          2.8           5.6          2.1
114           5.8          2.8           5.1          2.4
..            ...          ...           ...          ...
133           6.3          2.8           5.1          1.5
137           6.4          3.1           5.5          1.8
72            6.3          2.5           4.9          1.5
140           6.7          3.1           5.6          2.4
37            4.9          3.1           1.5          0.1

[120 rows x 4 columns]

In [33]:
y_train

91     0
135    0
69     0
128    0
114    0
      ..
133    0
137    0
72     0
140    0
37     1
Name: class_Iris-setosa, Length: 120, dtype: uint8

In [34]:
X_train = X_train.to_numpy()
y_train = y_train.to_numpy()
X_test = X_test.to_numpy()
y_test = y_test.to_numpy()

In [35]:
print(X_train[5].shape)

(4,)


## Initialising Weights and Bias

In [36]:
weights_1 = np.random.rand(len(X_train[0]))
weights_2 = np.random.rand(len(X_train[0]))
weights_3 = np.random.rand(len(X_train[0]))
print(weights_1)
bias_1 = np.random.rand()
bias_2 = np.random.rand()
bias_3 = np.random.rand()

[0.44304123 0.67867013 0.7329756  0.54497259]


## Training the Perceptron

In [37]:
def predict(input, weights, bias):
    weighted_sum = np.dot(input, weights) + bias
    output = 1 if weighted_sum > 0 else 0
    return output

In [38]:
def train(epochs, learning_rate, input, target, weights, bias):
    for j in range(epochs):
        for i in range(len(input)):
            prediction = predict(input[i], weights, bias)
            error = target[i] - prediction
            weights += learning_rate * error * input[i]
            bias += learning_rate * error

In [39]:
train(10, 0.01, X_train, y_train, weights_1, bias_1)

In [40]:
print(weights_1)
print(bias_1)
print(predict([5.0,3.3,1.4,0.2], weights=weights_1, bias=bias_1))

[-0.30495877  0.45967013 -0.1540244   0.19597259]
0.5582423357937422
1


## Testing

In [41]:
def test(test_set, test_output):
    correct_pred = 0
    result = []
    for i in range(len(test_set)):
        prediction = predict(test_set[i], weights=weights_1, bias=bias_1)
        result.append(prediction)
        if prediction == test_output[i]:
            correct_pred += 1
    print(np.array(result))
    print(test_output)
    print("Correct Prediction: ", correct_pred)
    print("Total tests: ", len(test_set))

In [42]:
test(X_test, y_test)

[1 0 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 0 1 1 0 0 0 1 0 0 1 1 0 0]
[1 0 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 0 1 1 0 0 0 1 0 0 1 1 0 0]
Correct Prediction:  30
Total tests:  30


In [43]:
print(11/30)

0.36666666666666664
